import express from "express";
import affiliate_routes from "./affiliates/affiliate_routes.js";
import article_routes from "./articles/article_routes.js";
import cart_routes from "./carts/cart_routes.js";
import category_routes from "./categorys/category_routes.js";
import chip_routes from "./chips/chip_routes.js";
import content_routes from "./contents/content_routes.js";
import email_routes from "./emails/email_routes.js";
import event_routes from "./events/event_routes.js";
import expense_routes from "./expenses/expense_routes.js";
import feature_routes from "./features/feature_routes.js";
import filament_routes from "./filaments/filament_routes.js";
import giftcard_routes from "./giftcards/giftcard_routes.js";
import image_routes from "./images/image_routes.js";
import order_routes from "./orders/order_routes.js";
import palette_routes from "./palettes/palette_routes.js";
import parcel_routes from "./parcels/parcel_routes.js";
import paycheck_routes from "./paychecks/paycheck_routes.js";
import payment_routes from "./payments/payment_routes.js";
import product_routes from "./products/product_routes.js";
import promo_routes from "./promos/promo_routes.js";
import shipping_routes from "./shippings/shipping_routes.js";
import survey_routes from "./surveys/survey_routes.js";
import team_routes from "./teams/team_routes.js";
import template_routes from "./templates/template_routes.js";
import ticket_routes from "./tickets/ticket_routes.js";
import token_routes from "./tokens/token_routes.js";
import tutorial_routes from "./tutorials/tutorial_routes.js";
import user_routes from "./users/user_routes.js";
import version_routes from "./versions/version_routes.js";
import wholesaler_routes from "./wholesalers/wholesaler_routes.js";

const router = express.Router();

router.use("/affiliates", affiliate_routes);
router.use("/articles", article_routes);
router.use("/carts", cart_routes);
router.use("/categorys", category_routes);
router.use("/chips", chip_routes);
router.use("/contents", content_routes);
router.use("/emails", email_routes);
router.use("/events", event_routes);
router.use("/expenses", expense_routes);
router.use("/features", feature_routes);
router.use("/filaments", filament_routes);
router.use("/giftcards", giftcard_routes);
router.use("/images", image_routes);
router.use("/orders", order_routes);
router.use("/palettes", palette_routes);
router.use("/parcels", parcel_routes);
router.use("/paychecks", paycheck_routes);
router.use("/payments", payment_routes);
router.use("/products", product_routes);
router.use("/promos", promo_routes);
router.use("/shippings", shipping_routes);
router.use("/surveys", survey_routes);
router.use("/teams", team_routes);
router.use("/templates", template_routes);
router.use("/tickets", ticket_routes);
router.use("/tokens", token_routes);
router.use("/tutorials", tutorial_routes);
router.use("/users", user_routes);
router.use("/versions", version_routes);
router.use("/wholesalers", wholesaler_routes);

export default router;
