"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = (function (props) {
    return "\n\n  <div class=\"placeorder\" style=\"display: flex;flex-wrap: wrap;justify-content: space-between;color: white;\">\n      <div class=\"placeorder-info\" style=\"box-sizing: border-box;flex: 3 1 60rem;\">\n        <div style=\"box-sizing: border-box;border-radius: 1rem;background-color: #8a8a8a;padding: 1rem;margin: 1rem;\">\n          <div\n            style=\"background-color: #8a8a8a;display: flex;justify-content: center;margin: 0px auto;box-sizing: border-box;\">\n            <h1 class=\"h1_title\"\n              style=\"background-color: #8a8a8a;display: flex;font-size: 40px;margin-bottom: 1vh;text-align: center;box-sizing: border-box;font-family: Helvetica;\">\n              Having trouble verifying your account?</h1>\n          </div>\n\n          <p style=\"background-color: #8a8a8a;text-align: center;box-sizing: border-box; font-size: 18px;\"> We\n            noticed that you created an account but have yet to verifiy it. Could you let us know if there is\n            anything we can do to help?</p>\n\n          <p style=\"background-color: #8a8a8a;text-align: center;box-sizing: border-box; font-size: 18px;\"> Is there\n            something wrong with the verification process? Does the process not make sense or work properly? </p>\n          <p style=\"background-color: #8a8a8a;text-align: center;box-sizing: border-box; font-size: 18px;\"> Please do\n            not hesitate to reach out to the Glow LEDs team for help. We are happy to assist you in anyway we can.</p>\n          <div style=\" width: 100%; display: flex; justify-content: center;\">\n            <button\n              style=\"background-color: #8a8a8a;border-radius: 5px;background-color: #676767;margin: 0 auto; margin-bottom: 10px;font-weight: bold;border: 0px;color: white;text-decoration: none;padding: 15px;box-sizing: border-box;font-size: 1.6rem;\"><a\n                style=\"font-size: 20px;color: white;text-decoration: none;box-sizing: border-box;\" href=\"" + (process.env
        .NODE_ENV === 'production'
        ? 'http://www.glow-leds.com'
        : 'http://localhost:3000') + "/pages/pages/contact/order_issues\">Contact</a></button>\n          </div>\n        </div>\n        <div style=\"box-sizing: border-box;border-radius: 1rem;background-color: #8a8a8a;padding: 1rem; margin: 1rem;\">\n          <div\n            style=\"background-color: #8a8a8a;display: flex;justify-content: center;flex-direction: column;margin-top: 10px;box-sizing: border-box;\">\n            <p style=\"background-color: #8a8a8a;text-align: center;box-sizing: border-box; font-size: 18px;\"> Please try\n              again to verify your email with the button or link provided below</p>\n            <button\n              style=\"background-color: #8a8a8a;border-radius: 5px;background-color: #676767;width: 155px;margin: 0 auto;font-weight: bold;border: 0px;color: white;text-decoration: none;padding: 15px;box-sizing: border-box;font-size: 1.6rem;\">\n              <a style=\"font-size: 20px;color: white;text-decoration: none;box-sizing: border-box;\" href=\"" + (process.env
        .NODE_ENV === 'production'
        ? 'http://www.glow-leds.com'
        : 'http://localhost:3000') + "/account/verified/" + props._id + "\">Verify\n                Email</a></button>\n            <p style=\"background-color: #8a8a8a; font-size: 18px;text-align: center;box-sizing: border-box;\">If the\n              \"Verifiy Email\"\n              button\n              doesn't work click\n              or\n              copy and paste this link\n              <a style=\"background-color: #8a8a8a;color: #8ce4ff;text-decoration: underline;box-sizing: border-box;\"\n                href=\" " + (process.env.NODE_ENV === 'production'
        ? 'http://www.glow-leds.com'
        : 'http://localhost:3000') + "/account/verified/" + props._id + "\">" + (process.env.NODE_ENV === 'production'
        ? 'http://www.glow-leds.com'
        : 'http://localhost:3000') + "/account/verified/" + props._id + "</a>\n              into\n              your browser to verify account\n            </p>\n\n          </div>\n        </div>\n        <div class=\"placeorder-action\"\n          style=\"box-sizing: border-box;flex: 1 1 20rem;border-radius: 1rem;background-color: #8a8a8a;padding: 1rem; margin: 1rem;margin-bottom: 10px;\">\n          <p style=\"background-color: #8a8a8a;text-align: center;box-sizing: border-box; font-size: 18px;\"> If you are\n            still unable to verify your account, please reach out and we will be able to manually verify you.</p>\n          <p style=\"background-color: #8a8a8a;text-align: center;box-sizing: border-box; font-size: 18px;\">If you are\n            recieving this and already have access to your account\n            please\n            ignore this email.\n          </p>\n        </div>\n      </div>\n\t";
});
