"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = (function (props) {
    return "\n\n  <div class=\"placeorder\" style=\"display: flex;flex-wrap: wrap;justify-content: space-between;color: white;\">\n  <div class=\"placeorder-info\" style=\"box-sizing: border-box;flex: 3 1 60rem;\">\n    <div style=\"box-sizing: border-box;border-radius: 1rem;background-color: #8a8a8a;padding: 1rem;margin: 1rem;\">\n      <div\n        style=\"background-color: #8a8a8a;display: flex;justify-content: center;margin: 0px auto;box-sizing: border-box;\">\n        <h1 class=\"h1_title\"\n          style=\"background-color: #8a8a8a;display: flex;font-size: 40px;margin-bottom: 1vh;text-align: center;box-sizing: border-box;font-family: Helvetica;\">\n          Verify Your Email Address</h1>\n      </div>\n      <div\n        style=\"background-color: #8a8a8a;display: flex;justify-content: center;margin: 0px auto;box-sizing: border-box;\">\n        <h1 class=\"h2_title\"\n          style=\"background-color: #8a8a8a;display: flex;font-size: 25px;text-align: center;box-sizing: border-box;font-family: Helvetica; font-size: 18px;\">\n          Hello, " + props.first_name + "\n        </h1>\n      </div>\n      <p style=\"background-color: #8a8a8a;text-align: center;box-sizing: border-box; font-size: 18px;\"> Thank you for registering\n        with\n        Glow LEDs. Please verify\n        your email address\n        by clicking below.</p>\n    </div>\n    <div style=\"box-sizing: border-box;border-radius: 1rem;background-color: #8a8a8a;padding: 1rem; margin: 1rem;\">\n      <div\n        style=\"background-color: #8a8a8a;display: flex;justify-content: center;flex-direction: column;margin-top: 10px;box-sizing: border-box;\">\n        <button\n          style=\"background-color: #8a8a8a;border-radius: 5px;background-color: #676767;width: 155px;margin: 0 auto;font-weight: bold;border: 0px;color: white;text-decoration: none;padding: 15px;box-sizing: border-box;font-size: 1.6rem;\">\n          <a style=\"font-size: 20px;color: white;text-decoration: none;box-sizing: border-box;\"\n            href=\"" + (process.env.NODE_ENV === 'production'
        ? 'http://www.glow-leds.com'
        : 'http://localhost:3000') + "/account/verified/" + props._id + "\">Verify\n            Email</a></button>\n        <p style=\"background-color: #8a8a8a; font-size: 18px;text-align: center;box-sizing: border-box;\">If the \"Verifiy Email\"\n          button\n          doesn't work click\n          or\n          copy and paste this link\n          <a style=\"background-color: #8a8a8a;color: #8ce4ff;text-decoration: underline;box-sizing: border-box;\"\n            href=\" " + (process.env.NODE_ENV === 'production'
        ? 'http://www.glow-leds.com'
        : 'http://localhost:3000') + "/account/verified/" + props._id + "\">" + (process.env.NODE_ENV === 'production'
        ? 'http://www.glow-leds.com'
        : 'http://localhost:3000') + "/account/verified/" + props._id + "</a>\n          into\n          your browser to verify account\n        </p>\n      </div>\n    </div>\n    <div class=\"placeorder-action\"\n      style=\"box-sizing: border-box;flex: 1 1 20rem;border-radius: 1rem;background-color: #8a8a8a;padding: 1rem; margin: 1rem;margin-bottom: 10px;\">\n      <p style=\"background-color: #8a8a8a;text-align: center;box-sizing: border-box; font-size: 18px;\">If you didn\u2019t request this,\n        please\n        ignore this email.\n        Your\n        email won\u2019t be verified until you access the link above.\n      </p>\n    </div>\n  </div>\n\t";
});
