export const EMAIL_CONFIRMATION_REQUEST = 'EMAIL_CONFIRMATION_REQUEST';
export const EMAIL_CONFIRMATION_SUCCESS = 'EMAIL_CONFIRMATION_SUCCESS';
export const EMAIL_CONFIRMATION_FAIL = 'EMAIL_CONFIRMATION_FAIL';

export const EMAIL_ORDER_REQUEST = 'EMAIL_ORDER_REQUEST';
export const EMAIL_ORDER_SUCCESS = 'EMAIL_ORDER_SUCCESS';
export const EMAIL_ORDER_FAIL = 'EMAIL_ORDER_FAIL';

export const EMAIL_SHIPPING_REQUEST = 'EMAIL_SHIPPING_REQUEST';
export const EMAIL_SHIPPING_SUCCESS = 'EMAIL_SHIPPING_SUCCESS';
export const EMAIL_SHIPPING_FAIL = 'EMAIL_SHIPPING_FAIL';

export const EMAIL_DELIVERED_REQUEST = 'EMAIL_DELIVERED_REQUEST';
export const EMAIL_DELIVERED_SUCCESS = 'EMAIL_DELIVERED_SUCCESS';
export const EMAIL_DELIVERED_FAIL = 'EMAIL_DELIVERED_FAIL';