export const REGISTRATION_EMAIL_REQUEST = 'REGISTRATION_EMAIL_REQUEST';
export const REGISTRATION_EMAIL_SUCCESS = 'REGISTRATION_EMAIL_SUCCESS';
export const REGISTRATION_EMAIL_FAIL = 'REGISTRATION_EMAIL_FAIL';

export const ORDER_EMAIL_REQUEST = 'ORDER_EMAIL_REQUEST';
export const ORDER_EMAIL_SUCCESS = 'ORDER_EMAIL_SUCCESS';
export const ORDER_EMAIL_FAIL = 'ORDER_EMAIL_FAIL';

export const SHIPPING_EMAIL_REQUEST = 'SHIPPING_EMAIL_REQUEST';
export const SHIPPING_EMAIL_SUCCESS = 'SHIPPING_EMAIL_SUCCESS';
export const SHIPPING_EMAIL_FAIL = 'SHIPPING_EMAIL_FAIL';

export const DELIVERY_EMAIL_REQUEST = 'DELIVERY_EMAIL_REQUEST';
export const DELIVERY_EMAIL_SUCCESS = 'DELIVERY_EMAIL_SUCCESS';
export const DELIVERY_EMAIL_FAIL = 'DELIVERY_EMAIL_FAIL';