export const FILAMENT_LIST_REQUEST = "FILAMENT_LIST_REQUEST";
export const FILAMENT_LIST_SUCCESS = "FILAMENT_LIST_SUCCESS";
export const FILAMENT_LIST_FAIL = "FILAMENT_LIST_FAIL";

export const MY_FILAMENT_LIST_REQUEST = "MY_FILAMENT_LIST_REQUEST";
export const MY_FILAMENT_LIST_SUCCESS = "MY_FILAMENT_LIST_SUCCESS";
export const MY_FILAMENT_LIST_FAIL = "MY_FILAMENT_LIST_FAIL";

export const FILAMENT_DETAILS_REQUEST = "FILAMENT_DETAILS_REQUEST";
export const FILAMENT_DETAILS_SUCCESS = "FILAMENT_DETAILS_SUCCESS";
export const FILAMENT_DETAILS_FAIL = "FILAMENT_DETAILS_FAIL";

export const FILAMENT_SAVE_REQUEST = "FILAMENT_SAVE_REQUEST";
export const FILAMENT_SAVE_SUCCESS = "FILAMENT_SAVE_SUCCESS";
export const FILAMENT_SAVE_FAIL = "FILAMENT_SAVE_FAIL";

export const FILAMENT_DELETE_REQUEST = "FILAMENT_DELETE_REQUEST";
export const FILAMENT_DELETE_SUCCESS = "FILAMENT_DELETE_SUCCESS";
export const FILAMENT_DELETE_FAIL = "FILAMENT_DELETE_FAIL";
