export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_REMOVE_STATE = 'ORDER_REMOVE_STATE';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const MY_ORDER_LIST_REQUEST = 'MY_ORDER_LIST_REQUEST';
export const MY_ORDER_LIST_SUCCESS = 'MY_ORDER_LIST_SUCCESS';
export const MY_ORDER_LIST_FAIL = 'MY_ORDER_LIST_FAIL';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';

export const ORDER_DELETE_REQUEST = 'ORDER_DELETE_REQUEST';
export const ORDER_DELETE_SUCCESS = 'ORDER_DELETE_SUCCESS';
export const ORDER_DELETE_FAIL = 'ORDER_DELETE_FAIL';

export const ORDER_REFUND_REQUEST = 'ORDER_REFUND_REQUEST';
export const ORDER_REFUND_SUCCESS = 'ORDER_REFUND_SUCCESS';
export const ORDER_REFUND_FAIL = 'ORDER_REFUND_FAIL';

export const ORDER_UPDATE_REQUEST = 'ORDER_UPDATE_REQUEST';
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS';
export const ORDER_UPDATE_FAIL = 'ORDER_UPDATE_FAIL';

// export const ORDER_SHIPPING_REQUEST = 'ORDER_SHIPPING_REQUEST';
// export const ORDER_SHIPPING_SUCCESS = 'ORDER_SHIPPING_SUCCESS';
// export const ORDER_SHIPPING_FAIL = 'ORDER_SHIPPING_FAIL';

// export const ORDER_MANUFACTURED_REQUEST = 'ORDER_MANUFACTURED_REQUEST';
// export const ORDER_MANUFACTURED_SUCCESS = 'ORDER_MANUFACTURED_SUCCESS';
// export const ORDER_MANUFACTURED_FAIL = 'ORDER_MANUFACTURED_FAIL';

// export const ORDER_PACKAGED_REQUEST = 'ORDER_PACKAGED_REQUEST';
// export const ORDER_PACKAGED_SUCCESS = 'ORDER_PACKAGED_SUCCESS';
// export const ORDER_PACKAGED_FAIL = 'ORDER_PACKAGED_FAIL';

// export const ORDER_DELIVERY_REQUEST = 'ORDER_DELIVERY_REQUEST';
// export const ORDER_DELIVERY_SUCCESS = 'ORDER_DELIVERY_SUCCESS';
// export const ORDER_DELIVERY_FAIL = 'ORDER_DELIVERY_FAIL';
