export const SPONSOR_LIST_REQUEST = 'SPONSOR_LIST_REQUEST';
export const SPONSOR_LIST_SUCCESS = 'SPONSOR_LIST_SUCCESS';
export const SPONSOR_LIST_FAIL = 'SPONSOR_LIST_FAIL';

export const SPONSOR_DETAILS_REQUEST = 'SPONSOR_DETAILS_REQUEST';
export const SPONSOR_DETAILS_SUCCESS = 'SPONSOR_DETAILS_SUCCESS';
export const SPONSOR_DETAILS_FAIL = 'SPONSOR_DETAILS_FAIL';

export const SPONSOR_SAVE_REQUEST = 'SPONSOR_SAVE_REQUEST';
export const SPONSOR_SAVE_SUCCESS = 'SPONSOR_SAVE_SUCCESS';
export const SPONSOR_SAVE_FAIL = 'SPONSOR_SAVE_FAIL';

export const SPONSOR_DELETE_REQUEST = 'SPONSOR_DELETE_REQUEST';
export const SPONSOR_DELETE_SUCCESS = 'SPONSOR_DELETE_SUCCESS';
export const SPONSOR_DELETE_FAIL = 'SPONSOR_DELETE_FAIL';
