// Remote
export const FETCH_TABLE_PAGE = 'FETCH_TABLE_PAGE';
export const FETCH_TABLE_PAGE_SUCCESS = 'FETCH_TABLE_PAGE_SUCCESS';
export const FETCH_TABLE_FILTERS = 'FETCH_TABLE_FILTERS';
export const FETCH_TABLE_FILTERS_SUCCESS = 'FETCH_TABLE_FILTERS_SUCCESS';
// Rows
export const ADD_ROWS = 'ADD_ROWS';
// Clear Table
export const CLEAR_TABLE = 'CLEAR_TABLE';
// Search
export const APPLY_SEARCH = 'APPLY_SEARCH';
// Sort
export const TOGGLE_SORT = 'TOGGLE_SORT';
// Row Dropdown
export const TOGGLE_ALL_DROPDOWN_ROWS = 'TOGGLE_ALL_DROPDOWN_ROWS';
export const TOGGLE_DROPDOWN_ROW = 'TOGGLE_DROPDOWN_ROW';
export const COLLAPSE_ALL_DROPDOWN_ROWS = 'COLLAPSE_ALL_DROPDOWN_ROWS';
// Reorder Rows
export const REORDER_ROWS_SUCCESS = 'REORDER_ROWS_SUCCESS';
// Pagination
export const UPDATE_PAGE = 'UPDATE_PAGE';
export const UPDATE_PAGE_SIZE = 'UPDATE_PAGE_SIZE';
// Row Selection
export const SELECT_ALL_ROWS = 'SELECT_ALL_ROWS';
export const SELECT_ROW = 'SELECT_ROW';
export const DESELECT_ROWS = 'DESELECT_ROWS';
// Slider
export const TOGGLE_SLIDER = 'TOGGLE_SLIDER';
export const CLOSE_SLIDER = 'CLOSE_SLIDER';
export const APPLY_URL_PARAMS = 'APPLY_URL_PARAMS';
// Row Selection
export const SELECT_ALL_DROPDOWN_ROWS = 'SELECT_ALL_DROPDOWN_ROWS';
export const SELECT_DROPDOWN_ROW = 'SELECT_DROPDOWN_ROW';
export const DESELECT_DROPDOWN_ROWS = 'DESELECT_DROPDOWN_ROWS';
// Filters
export const UPDATE_FILTER_DISPLAY = 'UPDATE_FILTER_DISPLAY';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const APPLY_FILTER = 'APPLY_FILTER';
export const APPLY_DATE_RANGE_FILTER = 'APPLY_DATE_RANGE_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const REMOVE_ALL_FILTERS = 'REMOVE_ALL_FILTERS';
export const APPLY_FILTER_SEARCH = 'APPLY_FILTER_SEARCH';
