import { IProduct } from "./productTypes";
import { IUser } from "./userTypes";

export interface ICart {
  cartItems?: ICartItem[];
  user?: IUser;
  deleted?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface CartItem {
  name?: string;
  qty?: number;
  display_image?: string;
  secondary_image?: string;
  color?: string;
  secondary_color?: string;
  color_group_name?: string;
  secondary_color_group_name?: string;
  color_code?: string;
  secondary_color_code?: string;
  price?: number;
  category?: string;
  pathname?: string;
  size?: number;
  preorder?: boolean;
  sale_price?: number;
  sale_start_date?: Date;
  sale_end_date?: Date;
  package_volume?: number;
  weight_pounds?: number;
  weight_ounces?: number;
  count_in_stock?: number;
  length?: number;
  width?: number;
  height?: number;
  package_length?: number;
  package_width?: number;
  package_height?: number;
  product?: IProduct;
  color_product?: IProduct;
  color_product_name?: string;
  secondary_color_product?: IProduct;
  secondary_color_product_name?: string;
  option_group_name: string;
  processing_time?: number;
  secondary_group_name?: string;
  option_product_name?: string;
  option_product?: IProduct;
  secondary_product_name?: string;
  secondary_product?: IProduct;
  createdAt?: Date;
  updatedAt?: Date;
}

export interface ICartItem {
  product: any;
  color_product: any;
  color_product_name: string;
  color_group_name: string;
  secondary_color_group_name: string;
  secondary_color_product: any;
  secondary_color_product_name: string;
  option_group_name: string;
  option_product: any;
  option_product_name: string;
  secondary_product: any;
  secondary_product_name: string;
  secondary_group_name: string;
  name: string;
  size: string;
  color: string;
  color_code: string;
  secondary_color: string;
  secondary_color_code: string;
  display_image: string;
  secondary_image: string;
  price: number;
  preorder: boolean;
  sale_price: number;
  sale_start_date: Date;
  sale_end_date: Date;
  count_in_stock: number;
  weight_pounds: number;
  weight_ounces: number;
  package_length: number;
  package_width: number;
  package_height: number;
  package_volume: number;
  processing_time: number;
  product_collection: string;
  pathname: string;
  collection: string;
  subcategory: string;
  category: string;
  qty: string;
  quantity: number;
  finite_stock: boolean;
  add_on_price: number;
  show_add_on: boolean;
}
