"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = (function (props) {
    var format_date_display = function (unformatted_date) {
        var date = new Date(unformatted_date);
        var day = date.getDate();
        var month = date.getMonth() + 1;
        var year = date.getFullYear();
        var formatted_date = month + "/" + day + "/" + year;
        return formatted_date;
    };
    console.log({ order_view_props: props });
    console.log({ order_view_props_order_items: props.orderItems });
    return "\n \n  <div class=\"placeorder\" style=\"display: flex;flex-wrap: wrap;justify-content: space-between;color: white;\">\n      <div class=\"placeorder-info\" style=\"box-sizing: border-box;flex: 3 1 60rem;\">\n        <div style=\"box-sizing: border-box;border-radius: 1rem;background-color: #8a8a8a;padding: 1rem;margin: 1rem;  margin-bottom: 0;\">\n          <div style=\"display: flex;justify-content: space-between; flex-direction: column;\">\n            <div style=\"display: block;flex-direction: column;box-sizing: border-box;\">\n              <h1 style=\"display: flex; width: 100%; font-size: 30px;margin-top: 0px; margin-bottom: 0px;box-sizing: border-box;font-family: Helvetica;\">\n                " + props.title + "</h1>\n                <div style=\" width: 100%;\">\n                  " + (props.title === 'Order Not Complete'
        ? "<div style=\" width: 100%;\"> \n                    <h3 >You have placed an order but have yet to pay.</h3>\n                    <h3 > When we recieve the payment we will start preparing your package for shipment. Thank you for your support!</h3>\n                    <button style=\"background-color: #8a8a8a;border-radius: 5px;background-color: #676767;margin: 0 auto; margin-bottom: 10px;font-weight: bold;border: 0px;color: white;text-decoration: none;padding: 15px;box-sizing: border-box;font-size: 1.6rem;\"><a style=\"font-size: 20px;color: white;text-decoration: none;box-sizing: border-box;\"href=\"" + (process
            .env.NODE_ENV === 'production'
            ? 'http://www.glow-leds.com'
            : 'http://localhost:3000') + "/secure/account/order/" + props._id + "\">Complete Order</a></button>\n        <h3>If the payment button does not show, please refresh the page.</h3>\n        <h3>Do you need assistance completing your order?</h3>\n                    <button style=\"background-color: #8a8a8a;border-radius: 5px;background-color: #676767;margin: 0 auto; margin-bottom: 10px;font-weight: bold;border: 0px;color: white;text-decoration: none;padding: 15px;box-sizing: border-box;font-size: 1.6rem;\"><a style=\"font-size: 20px;color: white;text-decoration: none;box-sizing: border-box;\"\n            href=\"" + (process.env.NODE_ENV === 'production'
            ? 'http://www.glow-leds.com'
            : 'http://localhost:3000') + "/pages/pages/contact/order_issues\">Contact</a></button>\n                  </div>"
        : "<div></div>") + "\n                </div>\n                <div style=\" display: flex;  flex-wrap: wrap; width: 100%;margin: 10px 0px;\">\n\n                <h2 style=\" font-size: 20px;margin: 0px; box-sizing: border-box;font-family: Helvetica;\"><strong>Order\n                    Number: </strong></h2>\n                <a href=\"" + (process.env.NODE_ENV === 'production'
        ? 'http://glow-leds.com'
        : 'http://localhost:3000') + "/secure/account/order/" + props._id + "\"\n                  style=\"color: white;text-decoration: none;box-sizing: border-box;\">" + props._id + "</a>\n              </div>\n            <div style=\"  display: flex;  flex-wrap: wrap;>\n              <h2 style=\"box-sizing: border-box;\"><strong>Date: </strong>  " + format_date_display(props.createdAt) + "</h2>\n            </div>\n              \n              </div>\n              </div>\n            </div>\n          </div>\n        </div>\n        <div class=\"placeorder-action\">\n      <div style=\"box-sizing: border-box;border-radius: 1rem;background-color: #8a8a8a;padding: 1rem; margin: 1rem;\">\n        <h1 style=\"box-sizing: border-box;font-family: Helvetica;  margin-top: 0;\">Shipping</h1>\n\n        <div style=\" width: 100%;\">\n\n          <div style=\"box-sizing: border-box;\">" + props.shipping.first_name + " " + props.shipping.last_name + "\n          </div>\n          <div style=\"box-sizing: border-box;\">" + props.shipping.address + "</div>\n          <div style=\"box-sizing: border-box;\">" + props.shipping.city + ", " + props.shipping.state + "\n            " + props.shipping.postalCode + " " + props.shipping.country + "</div>\n          " + (props.shipping.international ? "<div style=\"box-sizing: border-box;\">International</div>" : "<div></div>") + "\n\n          <div style=\"box-sizing: border-box; text-decoration: none; color: white;\">" + props.shipping.email + "</div>\n          <div style=\"    border-top: 0.1rem solid white;width: 100%;\">\n            <label style=\"margin-top: 10px;box-sizing: border-box;\"><strong>" + props.shipped + "</strong></label>\n          </div>\n        </div>\n      </div>\n    </div>\n        <div style=\"box-sizing: border-box;border-radius: 1rem;background-color: #8a8a8a;padding: 1rem; margin: 1rem;\">\n          <ul class=\"cart-list-container\"\n            style=\"margin-top: 0px;box-sizing: border-box;padding: 0;list-style-type: none;margin-right: 10px;\">\n            <li\n              style=\"box-sizing: border-box;display: flex;justify-content: space-between;padding-bottom: 1rem;margin-bottom: 1rem;border-bottom: .1rem #c0c0c0 solid;align-items: flex-end;\">\n              <h1 style=\"box-sizing: border-box;font-family: Helvetica;\">Shopping Cart</h1>\n              <div style=\"box-sizing: border-box;\">Price</div>\n            </li>\n            " + props.orderItems.map(function (item) {
        var item_item = "<li\n              style=\"box-sizing: border-box;display: flex;justify-content: space-between;padding-bottom: 1rem;margin-bottom: 1rem;border-bottom: .1rem #c0c0c0 solid;\">\n              <div style=\"display:flex; width: 100%;\">\n                <div class=\"cart-image\" style=\"box-sizing: border-box;\">\n                  <img src=\"" + (process.env.NODE_ENV === 'production'
            ? 'http://glow-leds.com'
            : 'http://localhost:3000') + item.display_image + "\" alt=\"product\"\n                    style=\"height: auto;\n                    width: 100%;box-sizing: border-box;max-width: 10rem;max-height: 10rem;border-radius: 1.5rem;margin-right: 10px;\">\n                </div>\n                <div class=\"cart-name\" style=\"box-sizing: border-box;\">\n                  <div style=\"box-sizing: border-box;\"><a href=\"" + (process.env.NODE_ENV === 'production'
            ? 'http://glow-leds.com'
            : 'http://localhost:3000') + "/collections/all/products/" + item.pathname + "\"\n                      style=\"box-sizing: border-box;text-decoration: none;color: white;\">" + item.name + "</a></div>\n                  <div style=\"box-sizing: border-box;\">Qty: " + item.qty + "</div>\n                </div>\n              </div>\n              <div class=\"cart-price\" style=\"box-sizing: border-box;text-align: right; width: 100px;\">\n                " + (item.sale_price !== 0
            ? "<div style=\"width: 100px;box-sizing: border-box;\">\n                  <del style=\"color: red;box-sizing: border-box;\">\n                    <label style=\"color: white;box-sizing: border-box;\">$" + (item.price ? item.price : item.price) + "</label>\n                  </del>{' '}\n                  <i class=\"fas fa-arrow-right\" style=\"box-sizing: border-box;\"></i> $" + (item.sale_price
                ? item.sale_price.toFixed(2)
                : item.sale_price) + "{' '}\n                  On Sale!\n                </div>"
            : "<label style=\"box-sizing: border-box;\">$" + (item.price
                ? item.price.toFixed(2)
                : item.price) + "</label>") + "\n              </div>\n            </li>";
        return item_item;
    }) + "\n          </ul>\n          <div style=\"display: flex;flex-direction: column;box-sizing: border-box;\">\n          <div for=\"order_note\" style=\"box-sizing: border-box;\">Order Note: </div>\n          <div style=\"box-sizing: border-box;\">" + props.order_note + "</div>\n        </div>\n        </div>\n      </div>\n      <div class=\"placeorder-action\"\n        style=\"box-sizing: border-box;flex: 1 1 20rem;border-radius: 1rem;background-color: #8a8a8a;padding: 1rem; margin: 1rem;margin-bottom: 10px;\">\n        <ul style=\"box-sizing: border-box;padding: 0;list-style-type: none;\">\n          <li style=\"box-sizing: border-box;display: flex;justify-content: space-between;margin-bottom: 1rem;\">\n            <h1 style=\"margin-top: 0px;box-sizing: border-box;font-family: Helvetica;\">Payment Summary</h1>\n          </li>\n          <li\n            style=\"box-sizing: border-box;display: flex; flex-wrap: wrap;justify-content: space-between;margin-bottom: 1rem;\">\n            <div style=\"box-sizing: border-box;\">Items</div>\n            <div style=\"box-sizing: border-box;\">$" + props.itemsPrice.toFixed(2) + "</div>\n          </li>\n          <li\n            style=\"box-sizing: border-box;display: flex; flex-wrap: wrap;justify-content: space-between;margin-bottom: 1rem;\">\n            <div style=\"box-sizing: border-box;\">Shipping</div>\n            <div style=\"box-sizing: border-box;\">$" + props.shippingPrice.toFixed(2) + "</div>\n          </li>\n          <li style=\"box-sizing: border-box; display: flex;flex-wrap: wrap;justify-content: space-between;margin-bottom: 1rem;\">\n            <div style=\"box-sizing: border-box;\">Tax</div>\n            <div style=\"box-sizing: border-box;\">$" + props.taxPrice.toFixed(2) + "</div>\n          </li>\n          <li style=\"box-sizing: border-box;display: flex;justify-content: space-between;margin-bottom: 1rem;\">\n            <div style=\"display: flex; flex-direction: column; width: 100%;\">\n            <div style=\"box-sizing: border-box; border-top: 0.1rem solid white;width: 100%; display: flex; flex-direction: column;\"><label>\n            </div>\n          </li>\n          <li\n          style=\"box-sizing: border-box;display: flex; flex-wrap: wrap;justify-content: space-between;margin-bottom: 1rem;\">\n          <div style=\"box-sizing: border-box;\">Order Total</div>\n          <div style=\"box-sizing: border-box;\">$" + props.totalPrice.toFixed(2) + "</div>\n        </li>\n          <li\n            style=\"box-sizing: border-box;display: flex; flex-wrap: wrap;justify-content: space-between;margin-bottom: 1rem;\">\n            <div style=\"box-sizing: border-box;\">" + props.paid + "</div>\n            <div style=\"box-sizing: border-box;\">" + props.token.card.brand + " ending in " + props.token.card.last4 + "</div>\n          </li>\n        </ul>\n      </div>\n    </div>\n\t";
});
