export { default as Product } from './Product';
export { default as Search } from './Search';
export { default as Sort } from './Sort';
export { default as Rating } from './Rating';
export { default as CheckoutSteps } from './CheckoutSteps';
export { default as PaypalButton } from './PaypalButton';
export { default as Reviews } from './Reviews';
export { default as Slideshow } from './Slideshow';
export { default as RelatedProducts } from './RelatedProducts';
export { default as SuggestedProducts } from './SuggestedProducts';
// export { default as Slider } from './Slider';
