// eslint-disable-next-line import/prefer-default-export
export const glTableReducersInitialState = {
  tableName: "",
  namespace: "",
  rows: [
    {
      job_group_template_name: "First JGT",
      job_group_id: 178,
      zone_name: "0323-Zone-Columbus location",
      job_group_rank: 0,
      serial_number: "test1",
      job_group_completion_status: 1,
      job_group_progress_percent: "0.0",
      delivery_date: "2023-11-03T00:00:00.000Z",
      priority_flag: 1,
      job_group_start_date: null,
      units: 1,
      product_model_name: "CO-10422 Product 1",
      jobs: [
        {
          rank: 38,
          job_id: 596,
          job_name: "Ola testing3",
          start_date: null,
          job_group_id: 178,
          completion_date: "2023-11-03T11:03:39.268167",
          lifecycle_status: 1,
          progress_percent: 0,
          workstation_name: "WS-0323-Zone-Columbus",
          completion_status: 3,
        },
        {
          rank: 39,
          job_id: 595,
          job_name: "test",
          start_date: null,
          job_group_id: 178,
          completion_date: "2023-11-03T11:03:39.268167",
          lifecycle_status: 1,
          progress_percent: 0,
          workstation_name: "WS-0323-Zone-Columbus",
          completion_status: 3,
        },
      ],
    },
  ],
  selectedRows: [],
  selectedRowObjects: [],
  selectedDropdownRows: [],
  selectedDropdownRowObjects: [],
  expandedRows: [],
  expandedRowObjects: [],
  nonTagFilters: ["workstation_name", "completion_status"],
  externalFilters: [],
  searchBy: "product_model_name",
  sorting: [0, "asc"],
  dropdownColumnDefs: [{}],
  availableFilters: {
    workstation_name: ["WS-0323-Zone-Columbus"],
    completion_status: [3, 2, 1],
  },
  filters: {
    workstation_name: [],
    completion_status: [],
  },
  filteredRows: [
    {
      job_group_template_name: "First JGT",
      job_group_id: 178,
      zone_name: "0323-Zone-Columbus location",
      job_group_rank: 0,
      serial_number: "test1",
      job_group_completion_status: 1,
      job_group_progress_percent: "0.0",
      delivery_date: "2023-11-03T00:00:00.000Z",
      priority_flag: 1,
      job_group_start_date: null,
      units: 1,
      product_model_name: "CO-10422 Product 1",
      jobs: [
        {
          rank: 38,
          job_id: 596,
          job_name: "Ola testing3",
          start_date: null,
          job_group_id: 178,
          completion_date: "2023-11-03T11:03:39.268167",
          lifecycle_status: 1,
          progress_percent: 0,
          workstation_name: "WS-0323-Zone-Columbus",
          completion_status: 3,
        },
        {
          rank: 39,
          job_id: 595,
          job_name: "test",
          start_date: null,
          job_group_id: 178,
          completion_date: "2023-11-03T11:03:39.268167",
          lifecycle_status: 1,
          progress_percent: 0,
          workstation_name: "WS-0323-Zone-Columbus",
          completion_status: 3,
        },
      ],
    },
  ],
  visibleRows: [
    {
      job_group_template_name: "First JGT",
      job_group_id: 178,
      zone_name: "0323-Zone-Columbus location",
      job_group_rank: 0,
      serial_number: "test1",
      job_group_completion_status: 1,
      job_group_progress_percent: "0.0",
      delivery_date: "2023-11-03T00:00:00.000Z",
      priority_flag: 1,
      job_group_start_date: null,
      units: 1,
      product_model_name: "CO-10422 Product 1",
      jobs: [
        {
          rank: 38,
          job_id: 596,
          job_name: "Ola testing3",
          start_date: null,
          job_group_id: 178,
          completion_date: "2023-11-03T11:03:39.268167",
          lifecycle_status: 1,
          progress_percent: 0,
          workstation_name: "WS-0323-Zone-Columbus",
          completion_status: 3,
        },
        {
          rank: 39,
          job_id: 595,
          job_name: "test",
          start_date: null,
          job_group_id: 178,
          completion_date: "2023-11-03T11:03:39.268167",
          lifecycle_status: 1,
          progress_percent: 0,
          workstation_name: "WS-0323-Zone-Columbus",
          completion_status: 3,
        },
      ],
    },
  ],
  page: 0,
  pageSize: 10,
  search: "",
  expandRow: "",
  menuOpen: false,
  menuSelection: null,
  filterSearch: "",
  remote: {
    isRemote: false,
    remotePageLoadingState: {},
    isRemoteLoading: false,
    lastRemoteFetchedPageId: 0,
    isLoadingFilters: false,
    remoteCount: null,
    latestRemoteVersionTimestamp: 0,
  },
  loading: false,
  columnDefs: [
    {
      title: "Rank",
      hidden: true,
    },
    {
      title: "Work Order",
    },
    {
      title: "Serial / WO #",
    },
    {
      title: "Priority",
    },
    {
      title: "Units",
    },
    {
      title: "Delivery Date",
    },
    {
      title: "",
      nonSortable: true,
    },
  ],
  booleanFilters: {},
};
