/* eslint-disable max-lines */
import { tagKeyMatchFull } from 'helpers/validationHelpers';
import React from 'react';

export const updateItemsData = {
  'items': [
    {
      'id': 10,
      'completion_status': 'Not Started',
      'rank': 0,
      'start_date': null,
      'completion_date': null,
      'job_template_id': 2,
      'product_model_id': 1065,
      'job_group_id': 3,
      'workstation_id': 3055,
      'created_at': '2023-09-26T18:57:23.218Z',
      'updated_at': '2023-09-26T20:31:31.237Z',
      'lifecycle_status': 'backlog',
      'workstation_name': 'CO-10422 Zone 1',
      'job_name': 'hello',
      'name': 'hello',
    },
    {
      'id': 6,
      'completion_status': 'Not Started',
      'rank': 2,
      'start_date': '2023-09-05T20:42:52.706Z',
      'completion_date': '2023-09-12T20:42:52.706Z',
      'job_template_id': 2,
      'product_model_id': 1065,
      'job_group_id': 3,
      'workstation_id': 15,
      'created_at': '2023-09-05T20:42:52.719Z',
      'updated_at': '2023-09-26T19:48:44.413Z',
      'lifecycle_status': 'backlog',
      'workstation_name': 'Test-1 WS (Columbus) via Zone Test-1 WS (Columbus)',
      'job_name': 'hello',
      'name': 'hello',
    },
    {
      'id': 5,
      'completion_status': 'Not Started',
      'rank': 1,
      'start_date': '2023-09-05T20:21:51.020Z',
      'completion_date': '2023-09-12T20:21:51.020Z',
      'job_template_id': 2,
      'product_model_id': 1065,
      'job_group_id': 3,
      'workstation_id': 15,
      'created_at': '2023-09-05T20:21:51.026Z',
      'updated_at': '2023-09-26T20:31:31.252Z',
      'lifecycle_status': 'backlog',
      'workstation_name': 'Test-1 WS (Columbus) via Zone Test-1 WS (Columbus)',
      'job_name': 'hello',
      'name': 'hello',
    },
  ],
  'orderAttribute': 'rank',
  'tableAttribute': 'lifecycle_status',
  'page': 0,
  'pageSize': 1,
  'columnId': 'backlog',
};

export const expectedUpdatedColumnData = [
  {
    'completion_date': null,
    'completion_status': 'Not Started',
    'created_at': '2023-09-26T18:57:23.218Z',
    'id': 10,
    'job_group_id': 3,
    'job_name': 'hello',
    'job_template_id': 2,
    'lifecycle_status': 'backlog',
    'name': 'hello',
    'product_model_id': 1065,
    'rank': 0,
    'start_date': null,
    'updated_at': '2023-09-26T20:31:31.237Z',
    'workstation_id': 3055,
    'workstation_name': 'CO-10422 Zone 1',
  },
  {
    'completion_date': '2023-09-12T20:42:52.706Z',
    'completion_status': 'Not Started',
    'created_at': '2023-09-05T20:42:52.719Z',
    'id': 6,
    'job_group_id': 3,
    'job_name': 'hello',
    'job_template_id': 2,
    'lifecycle_status': 'backlog',
    'name': 'hello',
    'product_model_id': 1065,
    'rank': 1,
    'start_date': '2023-09-05T20:42:52.706Z',
    'updated_at': '2023-09-26T19:48:44.413Z',
    'workstation_id': 15,
    'workstation_name': 'Test-1 WS (Columbus) via Zone Test-1 WS (Columbus)',
  },
  {
    'completion_date': '2023-09-12T20:21:51.020Z',
    'completion_status': 'Not Started',
    'created_at': '2023-09-05T20:21:51.026Z',
    'id': 5,
    'job_group_id': 3,
    'job_name': 'hello',
    'job_template_id': 2,
    'lifecycle_status': 'backlog',
    'name': 'hello',
    'product_model_id': 1065,
    'rank': 2,
    'start_date': '2023-09-05T20:21:51.020Z',
    'updated_at': '2023-09-26T20:31:31.252Z',
    'workstation_id': 15,
    'workstation_name': 'Test-1 WS (Columbus) via Zone Test-1 WS (Columbus)',
  },
];

export const initialState = {
  glTable: {
    rows: [
      {
        tag_key: 'alesley',
        tag_values: ['alesleyvalue'],
        locations: ['6535 - Location 1', 'Charlotte'],
      },
      {
        tag_key: 'archive56401',
        tag_values: ['archive56401-1', 'archive56401-2', 'archive56401-3'],
        locations: [
          '6535 - Location 1',
          '6535 - Location 2',
          '6535 - Location 3',
          'ACSC',
          'API Neg location',
          'Asheville',
          'Columbus',
        ],
      },
      {
        tag_key: 'atag',
        tag_values: ['1'],
        locations: ['6535 - Location 1', 'Columbus'],
      },
      {
        tag_key: 'atag2',
        tag_values: ['a', 'b', 'c'],
        locations: ['ACSC', 'Asheville', 'Charlotte', 'Columbus'],
      },
      {
        tag_key: 'char',
        tag_values: ['123tag_name-123#', 'asdfgh', 'qwerty', 'zxcvbn'],
        locations: ['Charlotte', 'Columbus', 'Elkhart', 'London'],
      },
      {
        tag_key: 'co3841',
        tag_values: ['tag2', 'tag3'],
        locations: ['Charlotte', 'Columbus'],
      },
      {
        tag_key: 'co3887removed',
        tag_values: ['sdfddsf', 'sdg', 'tag1'],
        locations: [
          '6535 - Location 1',
          '6535 - Location 2',
          '6535 - Location 3',
          'ACSC',
          'Charlotte',
          'Columbus',
          'Elkhart',
        ],
      },
      {
        tag_key: 'co66661',
        tag_values: ['value1'],
        locations: ['Asheville', 'Columbus'],
      },
      {
        tag_key: 'co7028',
        tag_values: ['test'],
        locations: ['Columbus'],
      },
      {
        tag_key: 'createdonobjectivemap',
        tag_values: ['1', '2', 'archive56401-3'],
        locations: ['Asheville', 'Charlotte', 'Columbus'],
      },
      {
        tag_key: 'dsgdfgfdg',
        tag_values: ['df', 'g'],
        locations: ['ACSC', 'Charlotte'],
      },
      {
        tag_key: 'evaltest1',
        tag_values: ['evaltest1'],
        locations: ['6535 - Location 1'],
      },
      {
        tag_key: 'expiration356days',
        tag_values: ['expiration365-1', 'expiration365-2', 'expiration365-3'],
        locations: ['6535 - Location 1', '6535 - Location 2', '6535 - Location 3', 'Charlotte', 'Columbus', 'Elkhart'],
      },
      {
        tag_key: 'expiration720days',
        tag_values: ['exp720-1', 'exp720-1-3', 'exp720-2'],
        locations: [
          '6535 - Location 1',
          '6535 - Location 2',
          '6535 - Location 3',
          'ACSC',
          'Asheville',
          'Charlotte',
          'Columbus',
        ],
      },
      {
        tag_key: 'group',
        tag_values: ['group_a', 'group_b', 'group_c'],
        locations: ['Asheville', 'Charlotte', 'Columbus', 'Rome'],
      },
      {
        tag_key: 'jobcode',
        tag_values: ['archive56401-1', 'archive56401-2', 'archive56401-3'],
        locations: ['Asheville', 'Charlotte', 'Columbus', 'LA'],
      },
      {
        tag_key: 'jobid',
        tag_values: ['001'],
        locations: ['LA'],
      },
      {
        tag_key: 'key0222',
        tag_values: ['k3', 'key0222value1'],
        locations: ['Charlotte', 'Elkhart'],
      },
      {
        tag_key: 'key0404',
        tag_values: ['key0404value1', 'key0404value2'],
        locations: ['Charlotte', 'Elkhart'],
      },
      {
        tag_key: 'key29861',
        tag_values: ['key29861-1'],
        locations: ['ACSC'],
      },
      {
        tag_key: 'newtag1',
        tag_values: ['newtag1-2'],
        locations: ['ACSC', 'Columbus'],
      },
      {
        tag_key: 'newtagnoselect',
        tag_values: ['newtagnoselect-1', 'newtagnoselect-2'],
        locations: ['ACSC', 'Asheville'],
      },
      {
        tag_key: 'qwwretreyre',
        tag_values: ['#test', '+#-_.'],
        locations: ['ACSC', 'Charlotte'],
      },
      {
        tag_key: 'slava',
        tag_values: ['slavatag1'],
        locations: ['Asheville', 'Columbus'],
      },
      {
        tag_key: 'sprintreview',
        tag_values: ['value1', 'value2'],
        locations: ['ACSC', 'Asheville', 'Charlotte', 'Columbus'],
      },
      {
        tag_key: 'svitlana',
        tag_values: ['sk3'],
        locations: ['Columbus'],
      },
      {
        tag_key: 'svitlana2',
        tag_values: ['sk-3'],
        locations: ['Columbus'],
      },
      {
        tag_key: 'tag1',
        tag_values: ['tag1-a', 'tag1-b'],
        locations: ['Columbus', 'Elkhart'],
      },
      {
        tag_key: 'tag101011',
        tag_values: ['tag101011-3'],
        locations: ['Charlotte'],
      },
      {
        tag_key: 'tag111',
        tag_values: ['archive56401-3', 'tag111-1', 'tag111-2', 'tag111-3'],
        locations: ['Columbus', 'Elkhart', 'LA', 'Newton', 'Rome'],
      },
      {
        tag_key: 'tag12821',
        tag_values: ['tag12821-1', 'tag12821-2'],
        locations: ['Columbus', 'Manchester', 'New York'],
      },
      {
        tag_key: 'tag2',
        tag_values: ['archive56401-3', 'tag2key1', 'tag2key2'],
        locations: ['6535 - Location 1', '6535 - Location 2', '6535 - Location 3', 'Charlotte', 'Columbus', 'Elkhart'],
      },
      {
        tag_key: 'tag3673obj1',
        tag_values: ['tag3673obj1-3'],
        locations: ['Elkhart'],
      },
      {
        tag_key: 'tag4556removed',
        tag_values: ['archive56401-3', 'bb'],
        locations: ['Charlotte', 'Columbus'],
      },
      {
        tag_key: 'tag50051',
        tag_values: ['tag50051-100'],
        locations: ['Asheville', 'Columbus'],
      },
      {
        tag_key: 'tag5268employee',
        tag_values: ['tag5268employee-1', 'tag5268employee-2'],
        locations: ['Asheville', 'Charlotte', 'Columbus', 'Elkhart'],
      },
      {
        tag_key: 'tag5690certbuilder',
        tag_values: ['c1', 'c2'],
        locations: ['Columbus', 'Elkhart'],
      },
      {
        tag_key: 'tag5690editempl',
        tag_values: ['b1', 'b2'],
        locations: ['Columbus', 'Elkhart'],
      },
      {
        tag_key: 'tag5690editemplonetoapply',
        tag_values: ['100', '1000', '10000', '200', '2000'],
        locations: [
          '6535 - Location 1',
          '6535 - Location 2',
          '6535 - Location 3',
          '6535 - Location 4',
          '6535 - Location 5',
          'ACSC',
          'Asheville',
          'Charlotte',
          'Columbus',
          'Elkhart',
        ],
      },
      {
        tag_key: 'tag5690objmap',
        tag_values: ['a1', 'a2', 'a3', 'a4', 'a5'],
        locations: ['Charlotte', 'Columbus', 'Elkhart', 'LA', 'Rome'],
      },
      {
        tag_key: 'tag5889',
        tag_values: ['evaluator'],
        locations: ['Columbus'],
      },
      {
        tag_key: 'tag5986fix',
        tag_values: ['tag5986fix-1'],
        locations: ['Charlotte'],
      },
      {
        tag_key: 'tag6460',
        tag_values: ['tag6460-1', 'tag6460-10', 'tag6460-2', 'tag6460-3', 'tag6460-4', 'tag6460-5'],
        locations: ['ACSC', 'Charlotte', 'Columbus', 'Elkhart', 'LA', 'London'],
      },
      {
        tag_key: 'tag64601',
        tag_values: ['tag64601-1', 'tag64601-2', 'tag64601-3'],
        locations: ['ACSC', 'Charlotte', 'Columbus'],
      },
      {
        tag_key: 'test',
        tag_values: ['gfdgfdgfd', 'test'],
        locations: ['ACSC', 'Asheville'],
      },
      {
        tag_key: 'test1',
        tag_values: ['test1ke3', 'test1key2', 'test1key5', 'test1key9', 'testkey1'],
        locations: [
          '6535 - Location 1',
          '6535 - Location 2',
          '6535 - Location 3',
          '6535 - Location 4',
          '6535 - Location 5',
          'Columbus',
        ],
      },
      {
        tag_key: 'test11',
        tag_values: ['test11k1', 'test11k2'],
        locations: ['Asheville', 'Columbus'],
      },
      {
        tag_key: 'test1312',
        tag_values: ['1qwrt'],
        locations: ['Columbus'],
      },
      {
        tag_key: 'test20',
        tag_values: ['derpawhat', 'test20k1', 'test20k2', 'test20k3'],
        locations: ['Asheville', 'Charlotte', 'Columbus', 'Elkhart'],
      },
      {
        tag_key: 'test3',
        tag_values: ['test3key1', 'test3key2', 'test3key3'],
        locations: ['ACSC', 'Charlotte', 'Columbus', 'Elkhart'],
      },
      {
        tag_key: 'test6',
        tag_values: ['a', 'd'],
        locations: ['Elkhart', 'New York'],
      },
      {
        tag_key: 'test7',
        tag_values: ['1'],
        locations: ['Elkhart'],
      },
      {
        tag_key: 'test9',
        tag_values: ['a', 'd'],
        locations: ['Charlotte', 'Elkhart'],
      },
      {
        tag_key: 'testak422',
        tag_values: ['1'],
        locations: ['Columbus'],
      },
      {
        tag_key: 'workstation',
        tag_values: ['value_should_not_be_removed'],
        locations: ['Columbus'],
      },
      {
        tag_key: 'ztag',
        tag_values: ['a'],
        locations: ['Columbus'],
      },
      {
        tag_key: 'zztop',
        tag_values: ['newesttagvalue', 'newtagvalue'],
        locations: ['6535 - Location 1', '6535 - Location 2', 'Columbus', 'Elkhart', 'Location-6531'],
      },
    ],
    permissions: [],
    filteredRows: [
      {
        tag_key: 'alesley',
        tag_values: ['alesleyvalue'],
        locations: ['6535 - Location 1', 'Charlotte'],
      },
      {
        tag_key: 'archive56401',
        tag_values: ['archive56401-1', 'archive56401-2', 'archive56401-3'],
        locations: [
          '6535 - Location 1',
          '6535 - Location 2',
          '6535 - Location 3',
          'ACSC',
          'API Neg location',
          'Asheville',
          'Columbus',
        ],
      },
      {
        tag_key: 'atag',
        tag_values: ['1'],
        locations: ['6535 - Location 1', 'Columbus'],
      },
      {
        tag_key: 'atag2',
        tag_values: ['a', 'b', 'c'],
        locations: ['ACSC', 'Asheville', 'Charlotte', 'Columbus'],
      },
      {
        tag_key: 'char',
        tag_values: ['123tag_name-123#', 'asdfgh', 'qwerty', 'zxcvbn'],
        locations: ['Charlotte', 'Columbus', 'Elkhart', 'London'],
      },
      {
        tag_key: 'co3841',
        tag_values: ['tag2', 'tag3'],
        locations: ['Charlotte', 'Columbus'],
      },
      {
        tag_key: 'co3887removed',
        tag_values: ['sdfddsf', 'sdg', 'tag1'],
        locations: [
          '6535 - Location 1',
          '6535 - Location 2',
          '6535 - Location 3',
          'ACSC',
          'Charlotte',
          'Columbus',
          'Elkhart',
        ],
      },
      {
        tag_key: 'co66661',
        tag_values: ['value1'],
        locations: ['Asheville', 'Columbus'],
      },
      {
        tag_key: 'co7028',
        tag_values: ['test'],
        locations: ['Columbus'],
      },
      {
        tag_key: 'createdonobjectivemap',
        tag_values: ['1', '2', 'archive56401-3'],
        locations: ['Asheville', 'Charlotte', 'Columbus'],
      },
      {
        tag_key: 'dsgdfgfdg',
        tag_values: ['df', 'g'],
        locations: ['ACSC', 'Charlotte'],
      },
      {
        tag_key: 'evaltest1',
        tag_values: ['evaltest1'],
        locations: ['6535 - Location 1'],
      },
      {
        tag_key: 'expiration356days',
        tag_values: ['expiration365-1', 'expiration365-2', 'expiration365-3'],
        locations: ['6535 - Location 1', '6535 - Location 2', '6535 - Location 3', 'Charlotte', 'Columbus', 'Elkhart'],
      },
      {
        tag_key: 'expiration720days',
        tag_values: ['exp720-1', 'exp720-1-3', 'exp720-2'],
        locations: [
          '6535 - Location 1',
          '6535 - Location 2',
          '6535 - Location 3',
          'ACSC',
          'Asheville',
          'Charlotte',
          'Columbus',
        ],
      },
      {
        tag_key: 'group',
        tag_values: ['group_a', 'group_b', 'group_c'],
        locations: ['Asheville', 'Charlotte', 'Columbus', 'Rome'],
      },
      {
        tag_key: 'jobcode',
        tag_values: ['archive56401-1', 'archive56401-2', 'archive56401-3'],
        locations: ['Asheville', 'Charlotte', 'Columbus', 'LA'],
      },
      {
        tag_key: 'jobid',
        tag_values: ['001'],
        locations: ['LA'],
      },
      {
        tag_key: 'key0222',
        tag_values: ['k3', 'key0222value1'],
        locations: ['Charlotte', 'Elkhart'],
      },
      {
        tag_key: 'key0404',
        tag_values: ['key0404value1', 'key0404value2'],
        locations: ['Charlotte', 'Elkhart'],
      },
      {
        tag_key: 'key29861',
        tag_values: ['key29861-1'],
        locations: ['ACSC'],
      },
      {
        tag_key: 'newtag1',
        tag_values: ['newtag1-2'],
        locations: ['ACSC', 'Columbus'],
      },
      {
        tag_key: 'newtagnoselect',
        tag_values: ['newtagnoselect-1', 'newtagnoselect-2'],
        locations: ['ACSC', 'Asheville'],
      },
      {
        tag_key: 'qwwretreyre',
        tag_values: ['#test', '+#-_.'],
        locations: ['ACSC', 'Charlotte'],
      },
      {
        tag_key: 'slava',
        tag_values: ['slavatag1'],
        locations: ['Asheville', 'Columbus'],
      },
      {
        tag_key: 'sprintreview',
        tag_values: ['value1', 'value2'],
        locations: ['ACSC', 'Asheville', 'Charlotte', 'Columbus'],
      },
      {
        tag_key: 'svitlana',
        tag_values: ['sk3'],
        locations: ['Columbus'],
      },
      {
        tag_key: 'svitlana2',
        tag_values: ['sk-3'],
        locations: ['Columbus'],
      },
      {
        tag_key: 'tag1',
        tag_values: ['tag1-a', 'tag1-b'],
        locations: ['Columbus', 'Elkhart'],
      },
      {
        tag_key: 'tag101011',
        tag_values: ['tag101011-3'],
        locations: ['Charlotte'],
      },
      {
        tag_key: 'tag111',
        tag_values: ['archive56401-3', 'tag111-1', 'tag111-2', 'tag111-3'],
        locations: ['Columbus', 'Elkhart', 'LA', 'Newton', 'Rome'],
      },
      {
        tag_key: 'tag12821',
        tag_values: ['tag12821-1', 'tag12821-2'],
        locations: ['Columbus', 'Manchester', 'New York'],
      },
      {
        tag_key: 'tag2',
        tag_values: ['archive56401-3', 'tag2key1', 'tag2key2'],
        locations: ['6535 - Location 1', '6535 - Location 2', '6535 - Location 3', 'Charlotte', 'Columbus', 'Elkhart'],
      },
      {
        tag_key: 'tag3673obj1',
        tag_values: ['tag3673obj1-3'],
        locations: ['Elkhart'],
      },
      {
        tag_key: 'tag4556removed',
        tag_values: ['archive56401-3', 'bb'],
        locations: ['Charlotte', 'Columbus'],
      },
      {
        tag_key: 'tag50051',
        tag_values: ['tag50051-100'],
        locations: ['Asheville', 'Columbus'],
      },
      {
        tag_key: 'tag5268employee',
        tag_values: ['tag5268employee-1', 'tag5268employee-2'],
        locations: ['Asheville', 'Charlotte', 'Columbus', 'Elkhart'],
      },
      {
        tag_key: 'tag5690certbuilder',
        tag_values: ['c1', 'c2'],
        locations: ['Columbus', 'Elkhart'],
      },
      {
        tag_key: 'tag5690editempl',
        tag_values: ['b1', 'b2'],
        locations: ['Columbus', 'Elkhart'],
      },
      {
        tag_key: 'tag5690editemplonetoapply',
        tag_values: ['100', '1000', '10000', '200', '2000'],
        locations: [
          '6535 - Location 1',
          '6535 - Location 2',
          '6535 - Location 3',
          '6535 - Location 4',
          '6535 - Location 5',
          'ACSC',
          'Asheville',
          'Charlotte',
          'Columbus',
          'Elkhart',
        ],
      },
      {
        tag_key: 'tag5690objmap',
        tag_values: ['a1', 'a2', 'a3', 'a4', 'a5'],
        locations: ['Charlotte', 'Columbus', 'Elkhart', 'LA', 'Rome'],
      },
      {
        tag_key: 'tag5889',
        tag_values: ['evaluator'],
        locations: ['Columbus'],
      },
      {
        tag_key: 'tag5986fix',
        tag_values: ['tag5986fix-1'],
        locations: ['Charlotte'],
      },
      {
        tag_key: 'tag6460',
        tag_values: ['tag6460-1', 'tag6460-10', 'tag6460-2', 'tag6460-3', 'tag6460-4', 'tag6460-5'],
        locations: ['ACSC', 'Charlotte', 'Columbus', 'Elkhart', 'LA', 'London'],
      },
      {
        tag_key: 'tag64601',
        tag_values: ['tag64601-1', 'tag64601-2', 'tag64601-3'],
        locations: ['ACSC', 'Charlotte', 'Columbus'],
      },
      {
        tag_key: 'test',
        tag_values: ['gfdgfdgfd', 'test'],
        locations: ['ACSC', 'Asheville'],
      },
      {
        tag_key: 'test1',
        tag_values: ['test1ke3', 'test1key2', 'test1key5', 'test1key9', 'testkey1'],
        locations: [
          '6535 - Location 1',
          '6535 - Location 2',
          '6535 - Location 3',
          '6535 - Location 4',
          '6535 - Location 5',
          'Columbus',
        ],
      },
      {
        tag_key: 'test11',
        tag_values: ['test11k1', 'test11k2'],
        locations: ['Asheville', 'Columbus'],
      },
      {
        tag_key: 'test1312',
        tag_values: ['1qwrt'],
        locations: ['Columbus'],
      },
      {
        tag_key: 'test20',
        tag_values: ['derpawhat', 'test20k1', 'test20k2', 'test20k3'],
        locations: ['Asheville', 'Charlotte', 'Columbus', 'Elkhart'],
      },
      {
        tag_key: 'test3',
        tag_values: ['test3key1', 'test3key2', 'test3key3'],
        locations: ['ACSC', 'Charlotte', 'Columbus', 'Elkhart'],
      },
      {
        tag_key: 'test6',
        tag_values: ['a', 'd'],
        locations: ['Elkhart', 'New York'],
      },
      {
        tag_key: 'test7',
        tag_values: ['1'],
        locations: ['Elkhart'],
      },
      {
        tag_key: 'test9',
        tag_values: ['a', 'd'],
        locations: ['Charlotte', 'Elkhart'],
      },
      {
        tag_key: 'testak422',
        tag_values: ['1'],
        locations: ['Columbus'],
      },
      {
        tag_key: 'workstation',
        tag_values: ['value_should_not_be_removed'],
        locations: ['Columbus'],
      },
      {
        tag_key: 'ztag',
        tag_values: ['a'],
        locations: ['Columbus'],
      },
      {
        tag_key: 'zztop',
        tag_values: ['newesttagvalue', 'newtagvalue'],
        locations: ['6535 - Location 1', '6535 - Location 2', 'Columbus', 'Elkhart', 'Location-6531'],
      },
    ],
    visibleRows: [
      {
        tag_key: 'alesley',
        tag_values: ['alesleyvalue'],
        locations: ['6535 - Location 1', 'Charlotte'],
      },
      {
        tag_key: 'archive56401',
        tag_values: ['archive56401-1', 'archive56401-2', 'archive56401-3'],
        locations: [
          '6535 - Location 1',
          '6535 - Location 2',
          '6535 - Location 3',
          'ACSC',
          'API Neg location',
          'Asheville',
          'Columbus',
        ],
      },
      {
        tag_key: 'atag',
        tag_values: ['1'],
        locations: ['6535 - Location 1', 'Columbus'],
      },
      {
        tag_key: 'atag2',
        tag_values: ['a', 'b', 'c'],
        locations: ['ACSC', 'Asheville', 'Charlotte', 'Columbus'],
      },
      {
        tag_key: 'char',
        tag_values: ['123tag_name-123#', 'asdfgh', 'qwerty', 'zxcvbn'],
        locations: ['Charlotte', 'Columbus', 'Elkhart', 'London'],
      },
      {
        tag_key: 'co3841',
        tag_values: ['tag2', 'tag3'],
        locations: ['Charlotte', 'Columbus'],
      },
      {
        tag_key: 'co3887removed',
        tag_values: ['sdfddsf', 'sdg', 'tag1'],
        locations: [
          '6535 - Location 1',
          '6535 - Location 2',
          '6535 - Location 3',
          'ACSC',
          'Charlotte',
          'Columbus',
          'Elkhart',
        ],
      },
      {
        tag_key: 'co66661',
        tag_values: ['value1'],
        locations: ['Asheville', 'Columbus'],
      },
      {
        tag_key: 'co7028',
        tag_values: ['test'],
        locations: ['Columbus'],
      },
      {
        tag_key: 'createdonobjectivemap',
        tag_values: ['1', '2', 'archive56401-3'],
        locations: ['Asheville', 'Charlotte', 'Columbus'],
      },
    ],
    selectedRows: [],
    selectedRowObjects: [],
    expandedRows: [],
    expandedRowObjects: [],
    sorting: [0, 'asc'],
    page: 0,
    pageSize: 10,
    availableFilters: {},
    availableFiltersProp: {
      locations: [
        '6535 - Location 1',
        'Charlotte',
        '6535 - Location 2',
        '6535 - Location 3',
        'ACSC',
        'API Neg location',
        'Asheville',
        'Columbus',
        'Elkhart',
        'London',
        'Rome',
        'LA',
        'Newton',
        'Manchester',
        'New York',
        '6535 - Location 4',
        '6535 - Location 5',
        'Location-6531',
      ],
    },
    filters: {
      locations: [],
    },
    remote: {},
    search: '',
    nonTagFilters: ['departments', 'locations'],
    searchBy: 'tag_key',
    columnDefs: [
      {
        title: 'Tag Key',
        display: function TaggingCell(row) {
          const { tag_key } = row;
          return <div className="name_td">{tag_key}</div>;
        },
        sortBy: row => row.tag_key,
        width: 200,
      },
      { title: 'Locations', display: row => row.locations?.join(', '), width: 100 },
    ],
    tableName: 'Tags',
    namespace: 'glTable',
    disableDropdownNoRecords: false,
    dropdownColumnDefs: [
      {
        title: 'Tag Value',
        display: (row, tagValueName) => tagValueName,
        sortBy: row => row,
        width: 200,
        colSpan: 2,
      },
    ],
    expandRow: '',
    enableRowSelect: false,
    enableDropdownRow: true,
    restrictSearchChars: e => {
      if (!tagKeyMatchFull(e.key)) {
        e.preventDefault();
        return false;
      }
      return e;
    },
    uniqueKey: 'tag_key',
    dropdownRowsUniqueKey: 'tag_values',
    searchPlaceholder: 'Search by Tag Name',
  },
};
