const routes = [
  { path: "/", component: "HomePage", exact: true },
  { path: "/account/changepassword", component: "ChangePasswordPage" },
  { path: "/account/register", component: "RegisterPage" },
  { path: "/account/passwordreset", component: "PasswordResetPage" },
  { path: "/account/resetpassword/:id", component: "ResetPasswordPage" },

  { path: "/checkout/placeorder", component: "PlaceOrderPage" },
  { path: "/checkout/shipping", component: "ShippingPage" },
  { path: "/checkout/cart/:pathname?", component: "CartPage" },
  { path: "/checkout/order/:id", component: "OrderPage", exact: true },

  { path: "/collections/all/products", component: "ProductsGridPage", exact: true },
  { path: "/collections/all/products/shop_by_chip", component: "ProductsGridByChipPage" },
  {
    path: "/collections/all/products/category/:category/subcategory/:subcategory/collection/:collection?",
    component: "ProductsGridPage",
  },
  { path: "/collections/all/products/category/:category/subcategory/:subcategory?", component: "ProductsGridPage" },
  { path: "/collections/all/products/category/:category", component: "ProductsGridPage" },
  { path: "/collections/all/products/:pathname", component: "ProductPage" },

  { path: "/collections/all/features/category/:category?", component: "FeaturesGridPage", exact: true },
  { path: "/collections/all/features/category/:category/:pathname?", component: "FeaturedPage", exact: true },

  { path: "/collections/all/sponsors/category/:category?", component: "SponsorsGridPage", exact: true },
  { path: "/collections/all/sponsors", component: "SponsorsGridPage", exact: true },
  { path: "/collections/all/sponsors/:promo_code?", component: "SponsorPage", exact: true },

  { path: "/collections/all/teams/category/:category?", component: "TeamsGridPage", exact: true },
  { path: "/collections/all/teams", component: "TeamsGridPage", exact: true },
  { path: "/collections/all/teams/:pathname?", component: "TeamPage", exact: true },

  { path: "/collections/all/tutorials/category/:category?", component: "TutorialsGridPage", exact: true },
  { path: "/collections/all/tutorials", component: "TutorialsGridPage", exact: true },

  { path: "/pages/announcements", component: "AnnouncementsPage", exact: true },
  { path: "/pages/manual/:pathname?", component: "ManualPage", exact: true },
  { path: "/pages/affiliate_terms", component: "AffiliateTermsPage", exact: true },
  { path: "/pages/color_palettes", component: "ColorPalettePage", exact: true },
  { path: "/pages/events", component: "EventsPage", exact: true },
  { path: "/pages/contact/:reason?", component: "ContactPage", exact: true },
  { path: "/pages/glowcontrol", component: "ContactPage" },
  { path: "/pages/terms", component: "TermsPage", exact: true },
  { path: "/pages/menu/:pathname", component: "MenuPage", exact: true },
  { path: "/pages/about", component: "AboutPage", exact: true },
  { path: "/pages/faq", component: "FAQPage", exact: true },
  { path: "/pages/sitemap", component: "SitemapPage", exact: true },
  { path: "/pages/music", component: "MusicPage", exact: true },
  { path: "/pages/track_your_order", component: "TrackOrderPage", exact: true },
  { path: "/pages/complete/:type/:id?", component: "CompletePage", exact: true },
];

const categories = [
  "Caps",
  "accessories",
  "batteries",
  "casings",
  "custom",
  "decals",
  "diffuser_caps",
  "diffusers",
  "exo_diffusers",
  "gift_card",
  "gloves",
  "glow_strings",
  "glowframez",
  "glowskins",
  "glowskinz",
  "glowstringz",
  "infinity_mirrors",
  "mega_diffuser_caps",
  "merch",
  "options",
  "shipping",
];
const subcategories = [
  "",
  "abstract",
  "batman",
  "battery_storage",
  "casings",
  "clip",
  "clips",
  "closed_hole",
  "clozd",
  "coin",
  "colors",
  "custom",
  "cylinders",
  "diffuser_adapters",
  "domes",
  "emoji",
  "fisheye",
  "geometric",
  "gift_card",
  "gloves",
  "imperfect",
  "leds",
  "mega_diffuser_adapters",
  "molecules",
  "novaskins_inovas_micromaxs",
  "open_hole",
  "options",
  "opyn",
  "outline",
  "patterns",
  "polygons",
  "polyhedrons",
  "refresh",
  "sacred_geometry",
  "sampler",
  "secondary_colors",
  "shapes",
  "shipping",
  "singles",
  "sizes",
  "starter_kit",
  "stickers",
  "storage",
  "symbol",
  "symbols",
  "universal",
];
const collections = [
  "",
  "capez",
  "classics",
  "colors",
  "festie_bestie",
  "fractal",
  "glowstringz",
  "nova",
  "novaframez",
  "novaskinz",
  "platonic_solids",
  "secondary_color",
  "secondary_colors",
  "sizes",
  "sleds",
  "space_cadet",
  "spheroid",
  "texture",
  "wholesale",
];
const pathnames = [
  "1225_batteries",
  "1225_coin_battery_dispenser",
  "1616_batteries",
  "1620_batteries",
  "1620_coin_battery_dispenser",
  "2016_batteries",
  "2x2_hexahedron_exo_diffusers",
  "3_sided_pyramid_diffusers",
  "4_sided_pyramid_diffusers",
  "alien_decals",
  "alien_diffuser_caps",
  "bullet_diffusers",
  "butteryfly_diffuser_caps",
  "capez",
  "clozd_alt_novaskinz",
  "clozd_apolloskinz_v2",
  "clozd_batman_decals",
  "clozd_coffinskinz_v2",
  "clozd_coinskinz_v2",
  "clozd_evoskinz_v2",
  "clozd_hybridskinz_coin_coffin_chips",
  "clozd_nanoskinz_v2",
  "clozd_novaframez",
  "clozd_novaskinz",
  "clozd_omniskinz",
  "clozd_omniskinz_sleds",
  "clozd_outline_batman_decals",
  "clozd_supernovaframez",
  "clozd_vortexskinz",
  "crescent_moon_diffuser_caps",
  "cylinder_diffusers",
  "diffuser_adapters",
  "diffuser_caps_adapters_starter_kit",
  "dodecahedron_exo_diffusers",
  "dodecahedron_face_diffuser_caps",
  "dodecahedron_point_diffuser_caps",
  "dome_diffusers",
  "double_chevron_decals",
  "festie_bestie_diffuser_caps",
  "fisheye_diffusers",
  "fisheye_dome_diffusers",
  "flashtip_diffusers",
  "flat_top_diffusers",
  "flower_diffuser_caps",
  "fractal_diffuser_caps",
  "gyrosphere_diffuser_caps",
  "half_dome_diffusers",
  "heart_decals",
  "heart_diffuser_caps",
  "hepta_fractal_diffuser_caps",
  "hexa_fractal_diffuser_caps",
  "hexahedron_diffuser_caps",
  "hexahedron_exo_diffusers",
  "hub_battery_backpack",
  "icosahedron_diffuser_caps",
  "icosahedron_exo_diffusers",
  "kaleidoscope_diffuser_caps",
  "lattice_diffuser_caps",
  "leaf_decals",
  "leaf_diffuser_caps",
  "mandala_diffuser_caps",
  "mega_3_sided_pyramid_diffusers",
  "mega_4_sided_pyramid_diffusers",
  "mega_bullet_diffusers",
  "mega_cube_diffusers",
  "mega_cylinder_diffusers",
  "mega_dome_diffusers",
  "mega_fisheye_dome_diffusers",
  "mega_triangle_diffusers",
  "mega_universal_battery_dispenser",
  "mesh_diffuser_caps",
  "micro_cylinder_diffusers",
  "micro_dome_diffusers",
  "mini_cube_diffusers",
  "mini_cylinder_diffusers",
  "mini_dome_diffusers",
  "mini_fisheye_diffusers",
  "mini_flashtip_diffusers",
  "mini_triangle_diffusers",
  "mountain_diffuser_caps",
  "mushroom_diffuser_caps",
  "nova_clip",
  "octahedron_diffuser_caps",
  "octahedron_exo_diffusers",
  "og_fisheye_diffusers",
  "opyn_apolloskinz_v2",
  "opyn_batman_decals",
  "opyn_coffinskinz_v2",
  "opyn_coinskinz_v2",
  "opyn_evoskinz_v2",
  "opyn_nanoskinz_v2",
  "opyn_outline_batman_decals",
  "opyn_vortexskinz",
  "peace_sign_diffuser_caps",
  "penta_fractal_diffuser_caps",
  "pinhole_diffusers",
  "platonic_solids_diffuser_caps",
  "platonic_solids_exo_diffusers",
  "popcorn_diffusers",
  "popcorn_pyramids_diffusers",
];

let generatedUrls = [];

routes.forEach(route => {
  if (route.path.includes(":category") && route.path.includes(":subcategory") && route.path.includes(":collection")) {
    categories.forEach(category => {
      let categoryUrl = route.path.replace(":category", category);
      subcategories.forEach(subcategory => {
        let subcategoryUrl = categoryUrl.replace(":subcategory", subcategory);
        collections.forEach(collection => {
          let collectionUrl = subcategoryUrl.replace(":collection", collection);
          generatedUrls.push(collectionUrl);
        });
      });
    });
  }
});

console.log(generatedUrls);
