name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run

      - name: Upload Cypress videos and screenshots as artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts
          path: client/cypress/videos, client/cypress/screenshots
