name: Cypress Tests

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install root dependencies
        run: npm install

      - name: Install client dependencies
        run: npm install --prefix client

      - name: Build backend
        run: npm run build

      - name: Build frontend
        run: CI=false npm run build --prefix client

      - name: Start Backend Server
        run: npm run start:prod &
        env:
          NODE_ENV: production

      - name: Serve Frontend
        run: npx serve -s client/build -l 3000 &

      - name: Run Cypress tests
        run: npm run cypress:run
        env:
          NODE_ENV: test
          REACT_APP_BUGSNAG_KEY: ${{ secrets.REACT_APP_BUGSNAG_KEY }}
          BUGSNAG_KEY: ${{ secrets.BUGSNAG_KEY }}
          CI: true

      - name: Upload Cypress videos and screenshots as artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts
          path: client/cypress/videos, client/cypress/screenshots
